* Treatment Recovery Kit
** Price
   $360.00
** Email Number With Image
   1
** Verbiage 
   Enhance your recovery & protect your investment!
   
   Laser treatments, chemicals peels, microdermabrasions, microneedling, IPL, etc. 
   All use corrective wounding to improve the skin. By injuring the skin, the body's
   natural healing response is triggered, which then improves the skin.
   
   skinBeautica's 3 Stage Post Procedure  Kit includes three products that enhance 
   each phase of the body's healing response. This is absolutely vital to optimize
   your results.
** Category
   Acne
   

* Three Step Post Procedure Kit
** Peptide 9
*** Price
    $147.00
*** Email Number With Image
    3
*** Verbiage
    *Remodelling Phase*

    Peptide-9 Remodelling Serum (TM) remodels your skin with new, organized collagen
    cells to give you smooth, clear skin. Also includes ingredients to firm elastin
    and reduce uneven pigmentation.
*** Category
    Acne Products

** EGF Recovery Serum
*** Price
    [ Not For Individual Sale ]
*** Email Number With Image
    5
*** Verbiage
    EGF Recovery Serum (TM) boosts your production of collagen cells through growth
    factors and stem cells. Also includes powerful antioxidants and ingredients 
    to boost cellular energy.
*** Category
    Acne Products
   
** Oxygen Plus Recovery Cream
*** Price
   $75.00
*** Email Number With Image
    7
*** Verbiage
   *None*
*** Category
    Acne Products
   

* Skin Refining Concentrate
** Price
   $58.00
** Email Number With Image
   9
** Verb age
   Skin Refining Concentrate is an advanced and powerful complex of vitamins (A, C, E), 
   natural algae, yeast extract, and herbal extracts. Our exclusive acid-free marine
   technology gently enhances skin's own shedding cycle to help visibly improve texture,
   reduce pore size, calm irritation, and soften fine lines. Helps to achieve a more even
   skin tone, calm over-reactive skin, and protect it from further damage.
** Category
   Anti Aging
   

* FadingGel With Kojic Acid
** Price
   $37.00
** Email Number With Image
   11
** Verbiage
   This light (oil-free) fading gel is recommended for all types of non-sensitive skin. 
   repeated use helps to reduce the appearance of dark spots and discolorations. Use of 
   sun protection is required to achieve desired results.
** Category
   Anti Aging
   

* Chamomile Cleansing Oil
** Price
   $43.00
** Email Number With Image
   13
** Verbiage
   This light, silky, water soluble natural oil blend gently melts, dissolves, and washes
   away heavy make up and impurities without stripping away natural oils. Combines 
   chamomile oil, lavender oil, and vitamin e to leave the skin feeling calm, clean 
   and refreshed. With addition of water it becomes a gentle milky cleanser. Rinses
   away clean, leaving no residue. Emulsifies and removes waterproof make up.
** Category
   Anti Aging


* Fading Cream
** Price
   $36.00
** Email Number With Image
   14
** Verbiage
   This is an excellent moisturizer and skin brightener, for non-oily skin types.
   It prevents moisture loss, while helping to lighten the skin. Best results are
   seen after 4-6 weeks of use.
** Category
   Anti Aging


* Cucumber Ice Sorbet
** Price
   [ Price ]
** Email Number With Image
   15
** Verbiage
   [ Verbiage already exists ]
** Category
   Anti Aging


* Collagen Elastin Cream
** Price
   $51.00
** Email Number With Image
   17
** Verbiage
   Collagen Elastin Cream is a high quality emollient and nourishing treatment cream
   which can be used as a day (under makeup) and night cream for normal, combination 
   and dry skin. Contains a blend of fine oils, natural hydrolyzed collagen, hydrolyzed
   elastin, carrot oil (natural vitamin A), chlorophyll, and botanical extracts. Soothes
   and softens the skin, helps to improve firmness and elasticity.
** Category
   Anti Aging
   

-> NEW STUFF HERE
* Collagen Day Cream
** Price
   $51.00
** Email Number With Image
   21
** Verbiage
   Collagen Day Cream is a luxurious and nourishing day cream recommended for normal
   and dry non-problem skin. It leaves skin soft and glowing and helps to prevent 
   the early appearance of wrinkles. Collagen Day Cream contains the finest hydrolyzed
   Collagen. It absorbs quickly and leaves a smooth, non-greasy finish, helps to 
   tighten the cell connections to improve firmness, and contains sun-screen ingredients
   for medium sun protection.
** Category
   Anti Aging


* Volcanic Mud Masque
** Price
   $26.00
** Email Number With Image
   23
** Verbiage
   Volcanic Mud Masque is a high performance treatment for dull and tired skin of all
   types. It draws out impurities as it cleanses, and it renews firmness and elasticity
   to the skin's surface. Regular use helps to achieve a smoother, fresher, and finer
   textured look.
** Category
   Anti Aging


* Glycolic Cream X-30
** Price
   $37.00
** Email Number With Image
   25
** Verbiage
   [ Needs Verbiage ] 
** Category
   Anti Aging
         

* Pineapple Enzyme Scrub
** Price
   $36.00
** Email Number With Image
   19
** Verbiage
   This is an effective exfoliating, retexturilizing, refining and nourishing 
   treatment scrub. Efficient and non-abrasive exfoliating is achieved by the 
   combination of Bromelain enzyme (which is obtained from pineapple) and the
   action of JoJoba beads. The enzyme helps to effectively remove excess surface
   cells, while the micro spherical beads dissolve and release their nourishing 
   Jojoba oil into the skin. This process produces improved skin texture and
   leaves the skin with a luminous glow. The ultimate result is refined and 
   moisturized skin.
** Category
   Anti Aging

* Juventus Signature Sponge
** Price
   $2.00 For One, $5.00 For Three
** Email Number With Image
   27
** Verbiage
   Natural Compressed  Celllulose Sponges... gentle natural living cell exfoliators.
   Each piece lasts about 2 weeks. Do not remove with make-up as these sponges
   will clog pores!
** Category
   Face Maintenance

* Clarifying Brightening Polish
** Price
   $57.00
** Email Number With Image
   28
** Verbiage
   This mild, brightening scrub with exfoliating micro-beads is specially formulated
   to gently cleanse and exfoliate by removing dry, dead skills cells, excess oils
   and residue to reveal healthier, younger looking skin. This cosmetically elegant
   formula provides antioxidant protective coverage, nourishing, enhances skin tone
   and texture, revealing a fresh and pure complexion.
** Category
   Anti-Aging
   
* Eye Make-Up Remover 
** Price
   $26.00
** Email Number With Image
   30
** Verbiage
   Eye make-up Remover is a light oil-free cleansing liquid especially formulated 
   for gentle removal of mascara and eye make-up from around the delicate eye 
   area.
** Category
   Face Maintenance
   
* Calming Mint Gel
** Price
   $27.00
** Email Number With Image
   31
** Verbiage
   Calming Mint Gel helps to  reduce and improve the appearance of unsightly razor
   bumps, razor burn, and ingrown hairs from shaving, electrolysis, and waxing. It 
   helps to soothe, soften, and condition the skin, while protecting against irritation.
   Great for bikini lines, underarms, legs, and men's face, neck, and back of head.
** Category
   Anti Aging
   
* Sheer Physical Sunscreen SPF 50+
** Price
   $42.00
** Email Number With Image
   33
** Verbiage
   Helps prevent sunburn if used as directed with other sun protection measures.
   Decreases the risk of skin cancer and early skin aging caused by the sun.
   Contains 13.75% zinc oxide.
** Category
   Face Maintenance
   
* Vitamin C Antioxidant Sunscreen
** Price
   $47.00
** Email Number With Image
   35
** Verbiage
   Helps prevent sunburn if used as directed with other sun protection measures.
   Decreases the risk of skin cancer and early skin aging caused by the sun.
   Contains 7.0% zinc oxide and 7.5% Octinoxate.
** Category
   Face Maintenance

* Clarifying Brightening Polish
** Price
   $57.00
** Email Number With Image
   36
** Verbiage
   This mild brightening scrub with exfoliating micro-beads is specially formulated 
   to gently cleanse and exfoliate by removing dry, dead skin cells, excess oils, and 
   residue to reveal healthier, younger looking skin. This cosmetically elegant formula
   provides antioxidant protective coverage, nourishes, enhances skin tone and texture,
   revealing a fresh and pure complexion.
** Category
   Anti Aging

