* Treatment Recovery Kit
** Price
   $360.00
** Email Number With Image
   1
** Verbage 
   Enhance your recovery & protect your investment!
   
   Laser treatments, chemicals peels, microdermabrasions, microneedling, IPL, etc. 
   All use corrective wounding to improve the skin. By injuring the skin, the body's
   natural healing response is triggered, which then improves the skin.
   
   skinBeautica's 3 Stage Post Procedure  Kit includes three products that enhance 
   each phase of the body's healing response. This is absolutely vital to optimize
   your results.
** Category
   Acne
   

* Three Step Post Procedure Kit
** Peptide 9
*** Price
    $147.00
*** Email Number With Image
    3
*** Verbage
    *Remodeling Phase*

    Peptide-9 Remodeling Serum (TM) remodels your skin with new, organized collagen
    cells to give you smooth, clear skin. Also includes ingredients to firm elastin
    and reduce uneven pigmentation.
*** Category
    Acne Products

** EGF Recovery Serum
*** Price
    [ Not For Individual Sale ]
*** Email Number With Image
    5
*** Verbage
    EGF Recovery Serum (TM) boosts your production of collagen cells through growth
    factors and stem cells. Also includes powerful antioxidants and ingredients 
    to boost cellular energy.
*** Category
    Acne Products
   
** Oxygen Plus Recovery Cream
*** Price
   $75.00
*** Email Number With Image
    7
*** Verbage
   *None*
*** Category
    Anti Aging
   

* Skin Refining Concentrate
** Price
   $58.00
** Email Number With Image
   9
** Verbage
   Skin Refining Concentrate is an advanced and powerful complex of vitamins (A, C, E), 
   natural algae, yeast extract, and herbald extracts. Our exclusive acid-free marine
   technology gently enhanceds skin's own shedding cycle to help visibly improve texture,
   reduce pore size, calm irritation, and soften fine lines. Helps to achieve a more even
   skin tone, calm over-reactive skin, and protect it from further damage.
** Category
   Anti Aging
   

* FadingGel With Kojic Acid
** Price
   $37.00
** Email Number With Image
   11
** Verbage
   This light (oil-free) fading gel is recommended for all types of non-sensitive skin. 
   repeated use helps to reduce the appearence of dark spots and discolorations. Use of 
   sun protection is required to achieve desired results.
** Category
   Anti Aging
   

* Chamomile Cleansing Oil
** Price
   $43.00
** Email Number With Image
   13
** Verbage
   This light, silky, water soluble natural oil blend gently melts, dissolves, and washes
   away heavy make up and impurities without stripping away natural oils. Combines 
   chamomile oil, lavender oil, and vitamin e to leave the skin feeling calm, clean 
   and refreshed. With addition of water it becomes a gentle milky cleanser. Rinses
   away clean, leaving no residue. Emulsifies and removes waterproof make up.
** Category
   Anti Aging


* Fading Cream
** Price
   $36.00
** Email Number With Image
   14
** Verbage
   This is an excellent moisturizer and skinn brightener, for non-oily skin types.
   It prevents moisture loss, while helping to lighten the skin. Best results are
   seen after 4-6 weeks of use.
** Category
   Anti Aging


* Cucumber Ice Sorbet
** Price
   [ Price ]
** Email Number With Image
   15
** Verbage
   [ Verbage already exists ]
** Category
   Anti Aging


* Collagen Elastin Cream
** Price
   $51.00
** Email Number With Image
   17
** Verbage
   Collagen Elastin Cream is a high quality emollient and nourishing treatment cream
   which can be used as a day (under makeup) and night cream for normal, combination 
   and dry skin. Contains a blend of fine oils, natural hydrolyzed collagen, hydrolyzed
   elastin, carrot oil (natural vitamin A), chlorophyll, and botanical extracts. Sooths
   and softens the skin, helps to improve firmness and elasticity.
** Category
   Anti Aging
   

* Pineapple Enzyme Scrub
** Price
   $36.00
** Email Number With Image
   19
** Verbage
   This is an effective exfoilating, retexturilizing, refining and nourishing 
   treatment scrub. Efficent and non-abrasive exfoilating is achieved by the 
   combination of Bromelain enzyme (which is obtained from pineapple) and the
   action of JoJoba beads. The enzyme helps to effectively remove excess surface
   cells, while the micro spherical beads dissove and release their nourishing 
   Jojoba oil into the skin. This process produces improved skin texture and
   leaves the skin with a luminous glow. The ultimate result is refined and 
   moisturized skin.
** Category
   Anti Aging
